### ISSUE TITLE
管理者ログインパスワードが正しいときと空のときに正常に動作していない

### ISSUE THREAD

**Issue by kshimizz** [tech-is/bbs_codeigniter_sample#3]
https://github.com/tech-is/bbs_codeigniter_sample/blob/ec8a336c99d90aa13de76c0b0dab28e97f6ac2de/src/application/controllers/Bbs.php#L158
の出力の後も、
https://github.com/tech-is/bbs_codeigniter_sample/blob/ec8a336c99d90aa13de76c0b0dab28e97f6ac2de/src/application/controllers/Bbs.php#L163
の出力の後も、`exit()`してないので、
https://github.com/tech-is/bbs_codeigniter_sample/blob/ec8a336c99d90aa13de76c0b0dab28e97f6ac2de/src/application/controllers/Bbs.php#L166
が出力される。
その結果、不正なjsonとなり、
https://github.com/tech-is/bbs_codeigniter_sample/blob/ec8a336c99d90aa13de76c0b0dab28e97f6ac2de/src/application/views/login_view.php#L25
で例外が発生する。

**Comment by Hironobu-Mori** [comment]
バグ修正ありがとうございました！
masterにマージ完了したので一旦閉じます！
